import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:trading_mobile/core/theme/app_colors.dart';
import 'package:trading_mobile/core/theme/app_typography.dart';
import 'package:trading_mobile/core/theme/tab_reference_metrics.dart';

void main() {
  test('covered tabs use deterministic measured ink and font roles', () {
    expect(AppColors.primary, const Color(0xFF007FFF));
    expect(AppColors.negative, const Color(0xFFE42D30));
    expect(AppColors.textPrimary, const Color(0xFF111111));
    expect(AppColors.textSecondary, const Color(0xFF5C5C60));
    expect(AppColors.historyOrderStatus, const Color(0xFF294675));
    expect(AppColors.historySegmentSelected, const Color(0xFFEDEDED));
    expect(AppTypography.plainFamily, 'Mt5Roboto');
    expect(AppTypography.condensedFamily, 'Mt5RobotoCondensed');
    expect(AppTypography.navigationLabel.fontSize, 9.5);
    expect(AppTypography.navigationLabel.height, 1);
    expect(AppTypography.quoteSymbol.fontSize, 16.5);
    expect(AppTypography.quoteSymbol.fontWeight, FontWeight.w700);
    expect(AppTypography.quoteSymbol.letterSpacing, -1.45);
    expect(AppTypography.quoteMeta.fontSize, 13.2);
    expect(AppTypography.quoteMeta.letterSpacing, .2);
    expect(AppTypography.quoteTimeMeta.letterSpacing, -.15);
    expect(AppTypography.quoteRangeMeta.letterSpacing, .55);
    expect(AppTypography.quoteBtcHighMeta.letterSpacing, .15);
    expect(AppTypography.quotePriceMajor.fontSize, 16.5);
    expect(AppTypography.quotePriceMajor.letterSpacing, .2);
    expect(AppTypography.quotePriceMinor.fontSize, 26);
    expect(AppTypography.quotePriceMinor.letterSpacing, .2);
    expect(AppTypography.chartTicketPriceMajor.fontSize, 16);
    expect(AppTypography.chartTicketPriceMajor.letterSpacing, -.8);
    expect(AppTypography.chartTicketPriceMinor.fontSize, 24);
    expect(AppTypography.chartTicketPriceMinor.letterSpacing, -.8);
    expect(AppTypography.tradeHeaderProfit.fontSize, 20);
    expect(AppTypography.tradeHeaderProfit.letterSpacing, -.3);
    expect(AppTypography.tradeMetric.fontSize, 16);
    expect(AppTypography.tradeMetricValue.letterSpacing, .5);
    expect(AppTypography.tradePositionPrimary.fontSize, 15.3);
    expect(AppTypography.tradePositionSecondary.fontSize, 16);
    expect(AppTypography.tradePositionSecondary.letterSpacing, .78);
    expect(AppTypography.tradePositionSecondary.color, AppColors.textSecondary);
    expect(AppTypography.tradePositionProfit.fontSize, 21);
    expect(AppTypography.tradePositionProfit.letterSpacing, -.1);
    expect(AppTypography.historyPrimary.fontSize, 16);
    expect(AppTypography.historyDealsSegment.fontSize, 14);
    expect(AppTypography.historyDealsSegment.letterSpacing, .15);
    expect(AppTypography.historyAction.letterSpacing, -.1);
    expect(AppTypography.historyTrailingPrimary.letterSpacing, -.2);
    expect(AppTypography.historySecondary.fontSize, 14);
    expect(AppTypography.historySecondary.letterSpacing, .1);
    expect(AppTypography.historyPriceRange.letterSpacing, 0);
    expect(AppTypography.historyTrailingSecondary.letterSpacing, .2);
    expect(AppTypography.historySummary.fontSize, 14.5);
    expect(AppTypography.historySummary.fontWeight, FontWeight.w400);
    expect(AppTypography.historySummaryValue.fontWeight, FontWeight.w400);
    expect(AppTypography.historySummaryValue.letterSpacing, .55);
    expect(AppTypography.historyOrderSummaryTotal.letterSpacing, .22);
  });

  test('canonical tab geometry remains explicit', () {
    expect(TabReferenceMetrics.viewportWidth, closeTo(393.3333333333, .0001));
    expect(TabReferenceMetrics.quoteRowHeight, 69.3333333333);
    expect(TabReferenceMetrics.quoteBtcMetaTop, 46);
    expect(TabReferenceMetrics.quoteBtcPriceScaleY, 1.07);
    expect(TabReferenceMetrics.quoteBtcPriceOffsetY, -1.3333333333);
    expect(TabReferenceMetrics.quoteBtcHighOffsetX, 1.3333333333);
    expect(TabReferenceMetrics.quoteCornerWidth, 8);
    expect(TabReferenceMetrics.quoteCornerHeight, 9.6666666667);
    expect(TabReferenceMetrics.quoteCornerOffsetY, .6666666667);
    expect(TabReferenceMetrics.tradeMetricRowHeight, 22);
    expect(TabReferenceMetrics.tradePositionRowHeight, 53.3333333333);
    expect(TabReferenceMetrics.tradePositionSecondaryTop, 22);
    expect(TabReferenceMetrics.historyRowHeight, 52);
    expect(TabReferenceMetrics.historySelectedSideInset, 3);
    expect(TabReferenceMetrics.historyDealsSelectedRightInset, 1);
    expect(TabReferenceMetrics.historyFirstSelectedLeftOffset, -1.3333333333);
    expect(TabReferenceMetrics.historyFirstSelectedRightInset, 2.6666666667);
    expect(TabReferenceMetrics.historyPrimaryTop, 4);
    expect(TabReferenceMetrics.historySecondaryTop, 26);
    expect(TabReferenceMetrics.historyPriceRangeTop, 26.6666666667);
    expect(TabReferenceMetrics.historyDealSecondaryTop, 27.3333333333);
    expect(TabReferenceMetrics.historyDealSecondaryScaleY, .9);
    expect(TabReferenceMetrics.historyActionOffsetY, .6666666667);
    expect(TabReferenceMetrics.historyOrderStatusScaleY, .85);
    expect(TabReferenceMetrics.historyOrderStatusOffsetX, -.6666666667);
    expect(TabReferenceMetrics.historyOrderStatusOffsetY, .6666666667);
    expect(TabReferenceMetrics.historyOrderSummaryTotalOffsetY, -.6666666667);
  });
}
